name: flow
description: A personal finance managing app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: "0.11.1+109"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  app_settings: ^5.1.1
  archive: ^4.0.2
  auto_size_text: ^3.0.0
  crop_image: ^1.0.12
  cross_file: ^0.3.3+8
  csv: ^6.0.0
  desktop_drop: ^0.5.0
  dotted_border: ^2.1.0
  dynamic_color: ^1.7.0
  file_picker: ^8.1.7
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_dynamic_icon_plus: ^1.2.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_markdown: ^0.7.4+2
  flutter_slidable: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_typeahead: ^5.2.0
  fuzzywuzzy: ^1.2.0
  geolocator: ^13.0.1
  go_router: ^14.6.2
  http: ^1.2.2
  image_picker: ^1.1.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  local_hero: ^0.3.0
  local_settings: ^0.5.0
  material_symbols_icons: ^4.2799.0
  moment_dart: ^3.3.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  pie_menu: ^3.2.0
  share_plus: ^10.0.0
  shared_preferences: ^2.3.1
  simple_icons: ^10.1.3
  smooth_page_indicator: ^1.1.0
  toastification: ^2.1.0
  url_launcher: ^6.2.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14

  flutter_launcher_icons: ^0.14.2

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  objectbox_generator: ^4.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/l10n/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

objectbox:
  output_dir: objectbox

flutter_launcher_icons:
  android: true
  min_sdk_android: 24
  adaptive_icon_background: "launcher_icons/adaptive_background.png"
  adaptive_icon_foreground: "launcher_icons/adaptive_foreground.png"
  ios: true
  image_path: "launcher_icons/flow.png"
  web:
    generate: true
    background_color: "#F9DFFF"
    theme_color: "#8500A6"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
