name: flow
description: A personal finance managing app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: "0.2.7+30"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  crop_image: ^1.0.12
  cross_file: ^0.3.3+8
  csv: ^5.1.1
  cupertino_icons: ^1.0.6
  desktop_drop: ^0.4.4
  file_picker: ^6.1.1
  file_saver: ^0.2.9
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0
  fuzzy: ^0.5.1
  go_router: ^13.2.0
  image_picker: ^1.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  local_settings: ^0.3.1
  mask_text_input_formatter: ^2.8.0
  material_symbols_icons: ^4.2719.1
  moment_dart: ^2.0.2
  month_picker_dialog: ^2.11.0
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # pie_menu: ^3.1.3
  pie_menu:
    git:
      url: https://github.com/sadespresso/flutter-pie-menu.git
  salomon_bottom_bar: ^3.3.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  simple_icons: ^10.1.3
  smooth_page_indicator: ^1.1.0
  toastification: ^1.2.0
  url_launcher: ^6.2.3
  uuid: ^4.2.2

dev_dependencies:
  build_runner: ^2.4.8

  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  objectbox_generator: ^2.3.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/l10n/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

objectbox:
  output_dir: objectbox

flutter_launcher_icons:
  android: true
  min_sdk_android: 24
  adaptive_icon_background: "launcher_icons/adaptive_background.png"
  adaptive_icon_foreground: "launcher_icons/adaptive_foreground.png"
  ios: true
  image_path: "launcher_icons/flow.png"
  web:
    generate: true
    background_color: "#F9DFFF"
    theme_color: "#8500A6"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
