name: flow
description: A personal finance managing app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: "0.13.5+215"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  app_settings: ^5.2.0
  archive: ^4.0.4
  auto_size_text: ^3.0.0
  crop_image: ^1.0.12
  connectivity_plus: ^6.1.3
  cross_file: ^0.3.3+8
  csv: ^6.0.0
  desktop_drop: ^0.5.0
  dotted_border: ^2.1.0
  file_picker: ^9.0.2
  file_saver: ^0.2.14
  fl_chart: ^0.70.0
  flutter:
    sdk: flutter
  flutter_dynamic_icon_plus: ^1.2.1
  flutter_floating_bottom_bar: ^1.2.0
  flutter_local_notifications: ^19.0.0-dev.7
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.0.0
  flutter_markdown: ^0.7.4+2
  flutter_slidable: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_timezone: ^4.0.0
  flutter_typeahead: ^5.2.0
  fuzzywuzzy: ^1.2.0
  geolocator: ^13.0.1
  go_router: ^14.8.0
  http: ^1.2.2
  icloud_storage: ^2.2.0
  image_picker: ^1.1.1
  in_app_review: ^2.0.10
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  local_auth: ^2.3.0
  local_hero: ^0.3.0
  local_settings: ^1.0.0
  logging: ^1.3.0
  logging_appenders: ^1.3.1
  material_symbols_icons: ^4.2805.1
  moment_dart: ^5.1.0
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  package_info_plus: ^8.3.0
  path: ^1.8.3
  path_provider: ^2.1.5
  pie_menu: ^3.2.10
  recurrence: ^0.0.9
  share_plus: ^10.0.0
  shared_preferences: ^2.5.2
  simple_icons: ^14.6.1
  smooth_page_indicator: ^1.1.0
  timezone: ^0.10.0
  toastification: ^3.0.1
  url_launcher: ^6.2.3
  uuid: ^4.5.1
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.14

  flutter_launcher_icons: ^0.14.2

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  objectbox_generator: ^4.0.1
  test: ^1.25.15

flutter:
  generate: true
  uses-material-design: true
  disable-swift-package-manager: true

  assets:
    - assets/
    - assets/fonts/
    - assets/l10n/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

objectbox:
  output_dir: objectbox

flutter_launcher_icons:
  android: true
  min_sdk_android: 24
  adaptive_icon_background: "launcher_icons/adaptive_background.png"
  adaptive_icon_foreground: "launcher_icons/adaptive_foreground.png"
  ios: true
  image_path: "launcher_icons/flow.png"
  web:
    generate: true
    background_color: "#F9DFFF"
    theme_color: "#8500A6"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
